remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Laura Weiwu
description: |
  <br><b>Post-Doctoral Fellow</b><br>
  Department of Economics<br>
  Stanford University<br>
  <br>
  <b>Assistant Professor</b> (in July 2025)<br>
  Haas School of Business<br>
  UC Berkeley<br>
  <br>
  <b>lauraweiwu@stanford.edu</b><br>
  <b>lauraww@berkeley.edu</b><br>
  <be>
  [CV](/assets/files/Laura_Weiwu_CV.pdf)
logo: /assets/images/laura-weiwu-crop.jpeg
