remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Laura Weiwu
description: |
  <b>Assistant Professor</b><br>
  Haas School of Business<br>
  UC Berkeley<br><br>
  2220 Piedmont Ave<br>
  Berkeley, CA 94720<br>
  <br>
  <b>[[lauraww@berkeley.edu||mailto:lauraww@berkeley.edu]]</b><br>
  <br>
  [[ [Curriculum Vitae]||/assets/files/Laura_Weiwu_CV.pdf]]
logo: /assets/images/laura-weiwu-crop.jpeg
include:
  - assets
